 Développeur Fullstack GO & Vue.JS 
 ---------------------------------
 
 Pour faire face au décollage de son activité et soutenue par une levée de fonds,
 My Bacchus recrute un Développeur Fullstack confirmé.
 
 LE POSTE
 --------
 
 Au sein d’une équipe de 15 personnes (dont 5 développeurs, 2 profils métiers) opérant en mode Agile,
 vous intervenez sur l’ensemble des étapes de la conception et du développement des applications web 
 permettant de piloter les équipements IoT, de collecter et d’analyser les données, …

Dans un contexte Agile, Cloud et en intégration continue, vos missions sont les suivantes

        définir les use-cases et établir des cahiers des charges (UML/SysML) 

        concevoir des architectures adaptées avec des règles de gestion appropriées 

        développer, maintenir, optimiser et déployer les solutions auxquelles vous contribuez 

        effectuer les tests unitaires et rédiger la documentation technique 

        intervenir sur les incidents constatés en production… 

        vous êtes moteur sur l’amélioration continue, les best-pracitces et la mise en place d’outils 
        d’automatisation 

Environnement technique : Cloud, Vue.js, Golang, BDD SQL, API REST/GraphQL, WebSocket, Python, Git… 


VOTRE PROFIL
------------

De formation BAC+2 à BAC+5, vous avez un minimum de 5 ans d’expérience sur un poste Fullstack.

Sur la partie front, vous avez une bonne maîtrise de Javascript.

Sur la partie backend, vous maîtrisez ou avez un fort intérêt pour Golang, le C ou le C++. 

ISP44

LES CONDITIONS
--------------

Poste CDI, basé à Saint-Herblain sur Nantes. Télétravail possible. 
